---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: manikandan1084/latest:new
        ports:
        - containerPort: 3000   

---
apiVersion: v1
kind: Service
metadata:
  name: cicd
spec:
  selector:
    app: cicd
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
