name: Deploy to ECR

on: workflow_dispatch

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    -  name: Build, tag, and push image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: app_ecr_new
         IMAGE_TAG: nodejs_demo_image
       run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .

    - name: Container Image Scanning with Trivy
      run: |
          # Scan your Docker image with Trivy here
          # Example command: trivy --exit-code 0 --severity HIGH --no-progress $ECR_REGISTRY/$ECR_REPOSITORY:nodejs_demo_image docker push $ECR_REGISTRY/$ECR_REPOSITORY:nodejs_demo_image
