name: Deploy to ECR

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install, build and test
        run: |
         npm install
         npm run build --if-present
         npm test

      - name: Docker Login
        uses: docker/login-action@v3.0.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
