name: Deploy

on:
  workflow_dispatch:

jobs:
  scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    container:
      image: node:16

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: --name sonarqube

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarQube Scanner
        run: |
          docker run --rm \
            -v "$(pwd):/usr/src" \
            -e SONAR_HOST_URL=http://sonarqube:9000 \
            -e SONAR_LOGIN=admin \
            -e SONAR_PASSWORD=admin \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=.
        continue-on-error: true
        
      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_LOGIN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          Push: true
          tags: manikandan1084/test:new
          
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.17.0
