name: Deploy to ECR

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust the AWS region as needed

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Build and Push Docker image with multiple tags
        run: docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/i5j2k0s0/app_ecr_new/app_ecr_new:${{ steps.timestamp.outputs.timestamp }} -t public.ecr.aws/i5j2k0s0/app_ecr_new/app_ecr_new:new-app --push .

