name: Deploy to Docker hub

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_LOGIN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: Dockerfile .
          Push: true
          tags: manikandan1084/test:new
          
