name: Deploy to Docker hub

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_LOGIN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          Push: true
          tags: manikandan1084/test:new2${{ github.event.inputs.tag }}

  deploy:
    name: Update deployment.yaml
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch deployment.yaml
        uses: actions/checkout@v2
        with:
          path: deploy

      - name: Update deployment.yaml
        run: |
          sed -i "s|manikandan1084/test:new|manikandan1084/manikandan1084/test:${{ github.event.inputs.tag }}|g" deploy/deployment.yaml


      
