name: Deploy to Docker hub

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
    
      - name: SonarQube Container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

      - name: Wait for SonarQube to Start
        run: sleep 30s 

      - name: SonarQube Scan
        run: |
          docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=admin \
            -Dsonar.password=admin \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=./
          
      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_LOGIN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          Push: true
          tags: manikandan1084/test:new2${{ github.event.inputs.tag }}

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.17.0

      
